apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliant
  namespace: team-platform-prod
spec:
  replicas: 1
  selector:
    matchLabels: {app: compliant}
  template:
    metadata:
      labels: {app: compliant}
    spec:
      containers:
      - name: good
        image: ghcr.io/secure-baseline/busybox:1.36-secure
        command: ["sleep","3600"]