apiVersion: apps/v1
kind: Deployment
metadata:
  name: noncompliant
  namespace: team-platform-prod
spec:
  replicas: 1
  selector:
    matchLabels: {app: noncompliant}
  template:
    metadata:
      labels: {app: noncompliant}
    spec:
      containers:
      - name: bad
        image: busybox:latest
        command: ["sleep","3600"]