apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-core
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./apps/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-ops
  targetNamespace: platform-system
  timeout: 2m0s